name: Parse examples

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
      - uses: actions/setup-python@v5
      - uses: actions/setup-node@v4
      - uses: tree-sitter/parser-test-action@v2
        with:
          test-rust: true
