name: Fuzz Parser

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run fuzzer
        uses: tree-sitter/fuzz-action@v4
        # with:
        #   tree-sitter-version: v0.22.5
